language: en-US
reviews:
  profile: assertive
  request_changes_workflow: false
  high_level_summary: true
  poem: false
  review_status: true
  collapse_walkthrough: false
  auto_review:
    enabled: true
    auto_incremental_review: true
  path_filters:
    - "!**/pnpm-lock.yaml"
    - "!**/yarn.lock"
    - "!**/package-lock.json"
    - "!**/dist/**"
    - "!**/cdk.out/**"
    - "!**/coverage/**"
    - "!**/*.min.js"
    - "!**/*.min.css"
  tools:
    shellcheck:
      enabled: true
    yamllint:
      enabled: true
    actionlint:
      enabled: true
    languagetool:
      enabled: true
      enabled_only: false
      level: default
    markdownlint:
      enabled: true
    hadolint:
      enabled: true
chat:
  auto_reply: true
