name: Geolonia Release (auto on vX.Y.Z tag)

on:
  push:
    tags:
      - 'v*.*.*'   # Only run on semver-like tags

jobs:
  publish:
    uses: geolonia/.github/.github/workflows/reusable-release-auto-on-tag.yml@v1
    secrets:
      WORKFLOWS_APP_ID: ${{ secrets.WORKFLOWS_APP_ID }}
      WORKFLOWS_APP_PRIVATE_KEY: ${{ secrets.WORKFLOWS_APP_PRIVATE_KEY }}
    # Optional settings (uncomment to override defaults):
    # with:
    #   move_major_tag: true
    #   move_minor_tag: true
    #   generate_release_notes: true
    #   prerelease: false
    #   tag_pattern: '^v([0-9]+)\.([0-9]+)\.([0-9]+)$'
